### ISSUE TITLE
Weekly Log for Elyasaf Boim

### ISSUE THREAD

**Issue by TomPalny** [TechnionYearlyProject/TheDoors#5]
This issue is meant to help in monitoring assignments in the project, progress, and volume of work.

Write here current tasks you are doing , as well as past work that is finished.

Whenever possible, please include an issue number that relates to the task you are writing.

Make use of the bulleted list as a way to organize things.

Have a great semester!

**Comment by elyasaf-boim** [comment]
week 7:
*installing pytest codecov  etc. and understanding the way it's works
* adding functions to the ManageDB - so we can test our feature #21 
*testing RoomRecommendation #21 
*writing tests for yarin & ilana feature #41

**Comment by elyasaf-boim** [comment]
week 8:

*fix the bugs in recommendation room (our feature) for sprint 1 #21
*add functions to Room class & fix some bugs 
*start with the friends logic part

**Comment by elyasaf-boim** [comment]
week 9 :
* Learning how to work with Bootstrap #53
* Learning HTML & CSS and try an example #63 
* choose design for the web - login page #57

**Comment by elyasaf-boim** [comment]
week 10:
* django - try to understand how it work and implement an example #67 
* start to design import rooms & import employees pages #75 
* fix some bugs so the build pass....

**Comment by elyasaf-boim** [comment]
week 12:

* Trying and succeeding to implement the system with Flask, helping all the team members to download it (and everythingelse needed) and explaining the team how it works and what to do.  #86 .
* Making the room search/update/delete pages with their logic and concatenation to the DB. #95
* room reccomendation page with its logic and concatenation to the DB. #100
* Designing, improving the GUI after using Flask. #87 #99
* Changing password (page+logic with flask) #105
* import files pages and logic with flask, influding error handling (s.a input is not csv file)
* export files page design and integration to DB in flask
* preparing the demo for the representation 4516f01
* redesigning and adding appropriate pages in the manager interface in order to make it easy to the user and easy to program #95
